//
//  Clipboard.swift
//  notch-911
//
//  macOS keeps exactly one thing on the clipboard: whatever you copied last.
//  Copy a second thing and the first is gone. This holds the last 15, so the
//  one you overwrote two minutes ago is still there to put back.
//
//  History lives in memory only — never on disk. Password managers, 2FA codes
//  and API tokens all go through the clipboard, and a file that quietly
//  accumulates them is a much worse thing to own than a shelf of screenshots.
//  Quitting the app is the guarantee that nothing survives.
//

import AppKit
import Foundation
import Observation

struct ClipItem: Identifiable, Hashable, Sendable {
    let id: UUID
    let text: String
    let copiedAt: Date
    /// Whitespace flattened to a single line and truncated. Precomputed because
    /// `text` never changes and the rows re-render on every hover.
    let preview: String

    init(text: String) {
        self.id = UUID()
        self.text = text
        self.copiedAt = Date()

        let flattened = text
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        self.preview = flattened.count > 160
            ? String(flattened.prefix(160)) + "…"
            : flattened
    }
}

@MainActor
@Observable
final class ClipboardStore {

    /// Fifteen, per the brief. Also about where a glanceable list stops being
    /// glanceable — past this you're scrolling to find things, and a search
    /// field would be the honest answer instead.
    static let maxItems = 15

    /// A copied entry is a preview row, not a document. Anything past this is
    /// held in full on the real pasteboard anyway until the next copy.
    private static let maxLength = 128 * 1024

    /// Apps that put secrets or throwaway values on the pasteboard mark them
    /// with these. Honouring the convention is the difference between a
    /// clipboard history and a password leak.
    private static let excludedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private(set) var items: [ClipItem] = []
    /// Set briefly after a row is copied back, so the row can confirm it.
    private(set) var recentlyCopied: UUID?

    @ObservationIgnored private(set) var isCapturing: Bool
    @ObservationIgnored private var pollTask: Task<Void, Never>?
    @ObservationIgnored private var flashTask: Task<Void, Never>?
    /// Injectable so the tests can drive a private pasteboard. Reaching for
    /// `.general` in a test would rewrite whatever the person running it had
    /// copied a moment earlier.
    @ObservationIgnored private let pasteboard: NSPasteboard
    /// Seeded from the current pasteboard so the thing that happened to be
    /// copied before launch isn't captured as if it were new.
    @ObservationIgnored private var lastChangeCount: Int

    init(pasteboard: NSPasteboard = .general, isCapturing: Bool = true) {
        self.pasteboard = pasteboard
        self.isCapturing = isCapturing
        self.lastChangeCount = pasteboard.changeCount
    }

    // MARK: Lifecycle

    /// `changeCount` is a single cheap call and the content is only read when it
    /// moves, so a 1s poll costs approximately nothing while idle. There is no
    /// change notification for `NSPasteboard` — polling is the only route.
    func start() {
        pollTask?.cancel()
        pollTask = Task { [weak self] in
            while !Task.isCancelled {
                guard let self else { return }
                capture()
                try? await Task.sleep(for: .seconds(1))
            }
        }
    }

    func stop() {
        pollTask?.cancel()
        pollTask = nil
        flashTask?.cancel()
        flashTask = nil
    }

    /// Turning capture off also drops what's held. "Stop recording but keep the
    /// recording" isn't what anyone reaching for this switch means.
    func setCapturing(_ capturing: Bool) {
        guard capturing != isCapturing else { return }
        isCapturing = capturing
        if !capturing { removeAll() }
    }

    // MARK: Capture

    /// Internal rather than private so the tests can step it deterministically
    /// instead of sleeping through poll intervals.
    func capture() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        // Advanced even while paused, so re-enabling starts from now rather than
        // back-filling whatever was copied while the switch was off.
        lastChangeCount = pasteboard.changeCount

        guard isCapturing, !isExcluded() else { return }
        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        record(String(text.prefix(Self.maxLength)))
    }

    private func isExcluded() -> Bool {
        guard let types = pasteboard.types else { return false }
        return Self.excludedTypes.contains { types.contains($0) }
    }

    private func record(_ text: String) {
        // Copying the same thing twice is one entry, moved back to the top —
        // otherwise a repeated copy pushes everything else off the end.
        items.removeAll { $0.text == text }
        items.insert(ClipItem(text: text), at: 0)
        if items.count > Self.maxItems {
            items.removeLast(items.count - Self.maxItems)
        }
    }

    // MARK: Mutation

    /// Puts an entry back on the real pasteboard, ready to paste.
    func copy(_ item: ClipItem) {
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        // Claim the change we just made. Without this the next poll would see
        // our own write and reshuffle the list under the pointer that clicked it.
        lastChangeCount = pasteboard.changeCount
        flashCopied(item.id)
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        if recentlyCopied == item.id { recentlyCopied = nil }
    }

    func removeAll() {
        items.removeAll()
        recentlyCopied = nil
    }

    private func flashCopied(_ id: UUID) {
        recentlyCopied = id
        flashTask?.cancel()
        flashTask = Task { [weak self] in
            try? await Task.sleep(for: .milliseconds(900))
            guard !Task.isCancelled else { return }
            self?.recentlyCopied = nil
        }
    }
}

// MARK: - View

import SwiftUI

/// At rest it's the last thing you copied. Focused — the peek's word for
/// "hovered", tracked one level up so the columns can get out of each other's
/// way — it takes width and height from its neighbours and opens the full list,
/// newest first, each row a button that puts that entry back on the pasteboard.
struct ClipboardView: View {
    let store: ClipboardStore
    /// The pointer is in this column: open, and take the room the others gave up.
    var isFocused = false
    /// The pointer is in a *different* column: shrink out of its way.
    var isMinimised = false
    var onHoverChange: (Bool) -> Void = { _ in }

    @State private var hovered: UUID?

    private static let restWidth: CGFloat = 176
    /// Focused, it takes back what the shelf and the centre column give up. The
    /// whole point of the focus dance is that a clipboard row is a line of text,
    /// and 176pt truncates almost everything worth recognising.
    private static let focusedWidth: CGFloat = 300
    private static let minimisedWidth: CGFloat = 116

    private static let rowHeight: CGFloat = 26
    private static let rowGap: CGFloat = 1
    /// Focused, the list stretches to hold all fifteen rather than scrolling.
    /// `NotchPanelController.panelSize` is sized to clear this plus the peek's
    /// own chrome — the two numbers move together.
    private static let maxOpenHeight: CGFloat = (rowHeight + rowGap) * 15
    /// …but it opens to a panel, not to however many rows happen to be held. A
    /// box that is two rows tall today and ten tomorrow is a different target
    /// every time you reach for it; six rows of room is one you can aim at.
    private static let minOpenHeight: CGFloat = (rowHeight + rowGap) * 6
    private static let reveal = Animation.spring(response: 0.34, dampingFraction: 0.84)

    private var width: CGFloat {
        if isMinimised { return Self.minimisedWidth }
        return isFocused ? Self.focusedWidth : Self.restWidth
    }

    private var showsList: Bool { isFocused && !store.items.isEmpty }

    private var listHeight: CGFloat {
        let needed = (Self.rowHeight + Self.rowGap) * CGFloat(store.items.count)
        return min(Self.maxOpenHeight, max(Self.minOpenHeight, needed))
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 7) {
            heading
            if showsList {
                list
                    .transition(.scale(scale: 0.94, anchor: .top).combined(with: .opacity))
            } else if let latest = store.items.first {
                row(latest)
                    .transition(.scale(scale: 0.94, anchor: .top).combined(with: .opacity))
            } else {
                empty
                    .transition(.scale(scale: 0.94, anchor: .top).combined(with: .opacity))
            }
        }
        .frame(width: width, alignment: .leading)
        .opacity(isMinimised ? 0.5 : 1)
        .animation(Self.reveal, value: store.items.count)
        .animation(Self.reveal, value: isFocused)
        .animation(Self.reveal, value: isMinimised)
        .contentShape(Rectangle())
        .onHover { hovering in
            onHoverChange(hovering)
            if !hovering { hovered = nil }
        }
    }

    // MARK: Pieces

    private var heading: some View {
        HStack(spacing: 4) {
            Image(systemName: store.items.isEmpty ? "clipboard" : "clipboard.fill")
            Text(store.items.isEmpty ? "Clipboard" : "\(store.items.count)/\(ClipboardStore.maxItems)")
            Spacer(minLength: 0)
            if showsList {
                Button { store.removeAll() } label: {
                    Image(systemName: "trash")
                }
                .buttonStyle(.plain)
                .accessibilityLabel("Clear clipboard history")
            }
        }
        .font(.caption2)
        .foregroundStyle(.white.opacity(0.35))
    }

    private var empty: some View {
        Text(store.isCapturing ? "Nothing copied yet" : "History off")
            .font(.caption)
            .foregroundStyle(.white.opacity(0.28))
            .frame(height: Self.rowHeight, alignment: .leading)
            .lineLimit(1)
    }

    /// Eager rows inside the scroller. Fifteen single-line rows cost nothing to
    /// lay out, and a `LazyVStack` would pop them in mid-expansion.
    private var list: some View {
        ScrollView(.vertical, showsIndicators: false) {
            VStack(alignment: .leading, spacing: Self.rowGap) {
                ForEach(store.items) { row($0) }
            }
        }
        .frame(height: listHeight, alignment: .top)
        .scrollBounceBehavior(.basedOnSize)
    }

    private func row(_ item: ClipItem) -> some View {
        let isCopied = store.recentlyCopied == item.id
        let isHovered = hovered == item.id

        return HStack(spacing: 5) {
            Text(item.preview)
                .font(.caption)
                .foregroundStyle(.white.opacity(isCopied ? 0.95 : 0.72))
                .lineLimit(1)
                .truncationMode(.tail)

            Spacer(minLength: 0)

            if isHovered && !isCopied {
                Button { store.remove(item) } label: {
                    Image(systemName: "xmark")
                        .font(.system(size: 9, weight: .semibold))
                        .foregroundStyle(.white.opacity(0.45))
                }
                .buttonStyle(.plain)
                .accessibilityLabel("Forget this entry")
            }

            // The affordance the whole feature hangs on: one click puts this
            // back on the pasteboard. The row is clickable too, but the icon is
            // what makes that discoverable.
            Button { store.copy(item) } label: {
                Image(systemName: isCopied ? "checkmark" : "doc.on.doc")
                    .font(.system(size: 10, weight: .semibold))
                    .foregroundStyle(.white.opacity(isCopied ? 0.95 : isHovered ? 0.7 : 0.35))
                    .frame(width: 13)
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Copy again")
        }
        .padding(.horizontal, 6)
        .frame(height: Self.rowHeight)
        .background(
            RoundedRectangle(cornerRadius: 5, style: .continuous)
                .fill(.white.opacity(isCopied ? 0.14 : isHovered ? 0.07 : 0.03))
        )
        .contentShape(Rectangle())
        .onTapGesture { store.copy(item) }
        .onHover { inside in
            if inside { hovered = item.id }
            else if hovered == item.id { hovered = nil }
        }
        .animation(.easeOut(duration: 0.14), value: isHovered)
        .animation(.easeOut(duration: 0.16), value: isCopied)
        .help(item.preview)
    }
}
