import AppKit
import Testing
@testable import notch_911

@Suite("Clipboard history")
@MainActor
struct ClipboardStoreTests {

    /// Every test gets its own named pasteboard, so nothing here touches what
    /// the person running the suite has copied.
    private func makeStore(
        isCapturing: Bool = true,
        _ name: String = #function
    ) -> (ClipboardStore, NSPasteboard) {
        let pasteboard = NSPasteboard(name: .init("com.aritra69.notch-911.tests.\(name)"))
        pasteboard.clearContents()
        let store = ClipboardStore(pasteboard: pasteboard, isCapturing: isCapturing)
        return (store, pasteboard)
    }

    private func put(_ text: String, on pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    // MARK: Capture

    @Test("Captures copies newest first")
    func capturesNewestFirst() {
        let (store, pasteboard) = makeStore()

        put("first", on: pasteboard)
        store.capture()
        put("second", on: pasteboard)
        store.capture()

        #expect(store.items.map(\.text) == ["second", "first"])
    }

    @Test("Ignores the pasteboard until it actually changes")
    func ignoresUnchangedPasteboard() {
        let (store, pasteboard) = makeStore()

        put("once", on: pasteboard)
        store.capture()
        store.capture()
        store.capture()

        #expect(store.items.count == 1)
    }

    @Test("Whatever was on the pasteboard before launch is not captured")
    func doesNotBackfillOnLaunch() {
        let pasteboard = NSPasteboard(name: .init("com.aritra69.notch-911.tests.preexisting"))
        pasteboard.clearContents()
        pasteboard.setString("copied before the app started", forType: .string)

        let store = ClipboardStore(pasteboard: pasteboard)
        store.capture()

        #expect(store.items.isEmpty)
    }

    @Test("Skips entries apps mark as concealed, transient or auto-generated",
          arguments: [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
          ])
    func skipsExcludedTypes(_ marker: String) {
        let pasteboard = NSPasteboard(name: .init("com.aritra69.notch-911.tests.\(marker)"))
        pasteboard.clearContents()
        let store = ClipboardStore(pasteboard: pasteboard)

        pasteboard.clearContents()
        pasteboard.setString("hunter2", forType: .string)
        pasteboard.setString("", forType: .init(marker))
        store.capture()

        #expect(store.items.isEmpty)
    }

    @Test("Skips blank copies")
    func skipsBlank() {
        let (store, pasteboard) = makeStore()

        put("   \n\t ", on: pasteboard)
        store.capture()

        #expect(store.items.isEmpty)
    }

    @Test("Holds no more than the cap, dropping the oldest")
    func capsHistory() {
        let (store, pasteboard) = makeStore()

        for index in 1...(ClipboardStore.maxItems + 5) {
            put("entry \(index)", on: pasteboard)
            store.capture()
        }

        #expect(store.items.count == ClipboardStore.maxItems)
        #expect(store.items.first?.text == "entry \(ClipboardStore.maxItems + 5)")
        #expect(store.items.last?.text == "entry 6")
    }

    @Test("Re-copying something already held moves it up rather than duplicating")
    func dedupesByMovingToFront() {
        let (store, pasteboard) = makeStore()

        for text in ["a", "b", "c"] {
            put(text, on: pasteboard)
            store.capture()
        }
        put("a", on: pasteboard)
        store.capture()

        #expect(store.items.map(\.text) == ["a", "c", "b"])
    }

    // MARK: Copying back

    @Test("Copying a row puts it back on the pasteboard")
    func copyWritesBack() throws {
        let (store, pasteboard) = makeStore()

        put("older", on: pasteboard)
        store.capture()
        put("newer", on: pasteboard)
        store.capture()

        let older = try #require(store.items.last)
        store.copy(older)

        #expect(pasteboard.string(forType: .string) == "older")
        #expect(store.recentlyCopied == older.id)
    }

    /// The list must not reshuffle under the pointer that just clicked it.
    @Test("Copying a row does not re-capture our own write")
    func copyDoesNotReorder() throws {
        let (store, pasteboard) = makeStore()

        for text in ["a", "b"] {
            put(text, on: pasteboard)
            store.capture()
        }
        let oldest = try #require(store.items.last)
        store.copy(oldest)
        store.capture()

        #expect(store.items.map(\.text) == ["b", "a"])
    }

    // MARK: Switching off

    @Test("Turning capture off clears what is held and stops recording")
    func disablingClears() {
        let (store, pasteboard) = makeStore()

        put("secret", on: pasteboard)
        store.capture()
        #expect(store.items.count == 1)

        store.setCapturing(false)
        #expect(store.items.isEmpty)

        put("while off", on: pasteboard)
        store.capture()
        #expect(store.items.isEmpty)
    }

    /// Re-enabling starts from now. Anything copied while the switch was off
    /// stays uncaptured even though it is still sitting on the pasteboard.
    @Test("Re-enabling does not back-fill what was copied while off")
    func reenablingDoesNotBackfill() {
        let (store, pasteboard) = makeStore()

        store.setCapturing(false)
        put("while off", on: pasteboard)
        store.capture()

        store.setCapturing(true)
        store.capture()
        #expect(store.items.isEmpty)

        put("after", on: pasteboard)
        store.capture()
        #expect(store.items.map(\.text) == ["after"])
    }

    // MARK: Rows

    @Test("Preview flattens newlines into one line")
    func previewIsOneLine() {
        let item = ClipItem(text: "  first line\n\tsecond   line\n\n third ")

        #expect(item.preview == "first line second line third")
        #expect(item.text == "  first line\n\tsecond   line\n\n third ")
    }

    @Test("Long previews are truncated but the entry keeps its full text")
    func previewTruncates() {
        let long = String(repeating: "x", count: 500)
        let item = ClipItem(text: long)

        #expect(item.preview.count == 161)
        #expect(item.preview.hasSuffix("…"))
        #expect(item.text.count == 500)
    }

    @Test("Forgetting one entry leaves the rest")
    func removesOne() throws {
        let (store, pasteboard) = makeStore()

        for text in ["a", "b", "c"] {
            put(text, on: pasteboard)
            store.capture()
        }
        let middle = try #require(store.items.first(where: { $0.text == "b" }))
        store.remove(middle)

        #expect(store.items.map(\.text) == ["c", "a"])
    }
}
